name: Build app and deploy to aliyun
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        node-version: '14'
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: './'
          REMOTE_HOST: '47.116.126.150'
          REMOTE_USER: root
          TARGET: /www/blog/serve-nest
